"""Local terminal-themed web UI.

Note: the task requires no website, and 00-requirements-intelligence.md lists a web frontend as
non-goal NG-01. This exists as an extra on top of the CLI, which remains the graded deliverable.
Nothing here reimplements pipeline logic -- it drives exactly the same functions the CLI does, so
the two cannot drift apart.

Binds to 127.0.0.1 only. It runs a face pipeline against a local camera and holds API keys in
process; it is not meant to be reachable from anywhere else.
"""

from __future__ import annotations

import json
import re
import secrets
import shutil
import threading
import traceback
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from fastapi import FastAPI, File, Header, HTTPException, Request, UploadFile
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse

from .config import Config, load_config
from .errors import (
    ChainError,
    FaceChainError,
    NoFaceDetectedError,
    NoVerifiedMatchError,
    SearchProviderError,
)

STATIC = Path(__file__).parent / "static"

# Root that user-supplied image paths are confined to.
PROJECT_ROOT = Path.cwd().resolve()
ALLOWED_SUFFIXES = {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".heic", ".heif"}


def _rel_to_project(path: Path) -> str:
    """Project-relative path with forward slashes.

    `pipeline.new_run_dir` returns a relative `artifacts/run-…` path. `Path.relative_to` on
    Python 3.11 raises if one side is relative and the other is the absolute PROJECT_ROOT.
    """
    resolved = path.resolve() if path.is_absolute() else (PROJECT_ROOT / path).resolve()
    return str(resolved.relative_to(PROJECT_ROOT)).replace("\\", "/")

# Per-process CSRF token. The page embeds it; API writes require it. A cross-origin script cannot
# read our HTML (no CORS is enabled), so it cannot obtain the token.
CSRF_TOKEN = secrets.token_urlsafe(32)

UPLOAD_DIR = PROJECT_ROOT / "uploads"
MAX_UPLOAD_BYTES = 12 * 1024 * 1024
POST_TEXT_CAP = 50_000
EVIDENCE_CAP = 200_000
ARTIFACT_FILES = {
    "probe.jpg": "image/jpeg",
    "probe_aligned.png": "image/png",
    "probe_head.png": "image/png",
    "candidate.jpg": "image/jpeg",
    "post_text.txt": "text/plain; charset=utf-8",
    "evidence.json": "application/json",
    "receipt.json": "application/json",
}
# Lens thumbnails stored next to the match. Names are generated by the pipeline, never the client.
_CANDIDATE_THUMB = re.compile(r"^candidates/c\d{3}\.jpg$")
POST_TEXT_BACKUP = "post_text.backup.txt"
EVIDENCE_BACKUP = "evidence.backup.json"

# In-process eth-tester is a new empty chain on every make_web3() call. Cache one for the
# website so local anchor and the later re-verify talk to the same records.
_LOCAL: dict[str, Any] = {}
# Magic bytes, checked against actual content rather than the declared type or the filename.
IMAGE_MAGIC = (
    b"\xff\xd8\xff", b"\x89PNG\r\n\x1a\n", b"GIF8", b"RIFF", b"BM",
    b"II*\x00", b"MM\x00*",
)


def _looks_like_image(head: bytes) -> bool:
    if any(head.startswith(m) for m in IMAGE_MAGIC):
        return True
    # HEIC/HEIF carry an ftyp box a few bytes in
    return len(head) > 12 and head[4:8] == b"ftyp"


def safe_run_dir(raw: str) -> Path:
    """Resolve a run directory, confined to the artifacts tree.

    Same reasoning as safe_image_path: the server is reachable by any local process and any page
    in the browser, so a caller-supplied path is untrusted regardless of the localhost bind.
    """
    if not raw:
        raise FaceChainError("no run directory given")
    resolved = (PROJECT_ROOT / Path(raw)).resolve()
    artifacts = (PROJECT_ROOT / "artifacts").resolve()
    try:
        resolved.relative_to(artifacts)
    except ValueError:
        raise FaceChainError("run directory must be inside artifacts/") from None
    if not resolved.is_dir():
        raise FaceChainError("run directory not found", {"path": raw})
    return resolved


def safe_image_path(raw: str) -> Path:
    """Resolve a user-supplied image path, confined to the project directory.

    Without this, a POST to the local API could name any image on disk -- and since the pipeline
    UPLOADS the probe to a public image host to run the search, that is file exfiltration rather
    than mere disclosure. The server is localhost-bound, which is not a defence: any page in the
    browser, or any local process, can reach it.
    """
    if not raw:
        raise FaceChainError("no input image")
    candidate = Path(raw).expanduser()
    resolved = (PROJECT_ROOT / candidate).resolve() if not candidate.is_absolute() else candidate.resolve()

    try:
        resolved.relative_to(PROJECT_ROOT)
    except ValueError:
        raise FaceChainError(
            "image must be inside the project directory",
            {"hint": "copy the file into the project folder and pass a relative path"},
        ) from None

    if resolved.suffix.lower() not in ALLOWED_SUFFIXES:
        raise FaceChainError(
            "unsupported image type", {"suffix": resolved.suffix, "allowed": "jpg png webp bmp heic"}
        )
    if not resolved.is_file():
        raise FaceChainError("image not found", {"path": str(candidate)})
    return resolved


@dataclass
class Job:
    id: str
    lines: list[dict] = field(default_factory=list)
    done: bool = False
    ok: bool = False
    result: dict[str, Any] | None = None

    def log(self, text: str, kind: str = "info") -> None:
        self.lines.append({"text": text, "kind": kind})


_jobs: dict[str, Job] = {}
_lock = threading.Lock()


def _web3(cfg: Config):
    """Public RPC is stateless; the in-process local chain must be reused in this process."""
    from .chain.deploy import make_web3

    if cfg.network != "local":
        return make_web3(cfg)
    w3 = _LOCAL.get("w3")
    if w3 is None:
        w3 = make_web3(cfg)
        _LOCAL["w3"] = w3
    return w3


def _contract_address(cfg: Config, payload: dict | None = None) -> str:
    raw = ""
    if payload:
        raw = str(payload.get("contract") or "").strip()
    if not raw and cfg.network == "local":
        raw = str(_LOCAL.get("contract") or "")
    if not raw:
        raw = str(cfg.contract_address or "")
    if not raw:
        cfg.require("contract_address")
    return raw


def _artifact_media_type(name: str) -> str | None:
    if name in ARTIFACT_FILES:
        return ARTIFACT_FILES[name]
    if _CANDIDATE_THUMB.fullmatch(name):
        return "image/jpeg"
    return None


def _artifact_inventory(run_dir: Path) -> dict[str, Any]:
    images = [
        n for n in ("probe.jpg", "probe_head.png", "probe_aligned.png", "candidate.jpg")
        if (run_dir / n).is_file()
    ]
    thumbs: list[str] = []
    cdir = run_dir / "candidates"
    if cdir.is_dir():
        for p in sorted(cdir.glob("c*.jpg")):
            rel = f"candidates/{p.name}"
            if _CANDIDATE_THUMB.fullmatch(rel):
                thumbs.append(rel)
    return {"images": images, "candidate_thumbs": thumbs}


def _ensure_backup(run_dir: Path) -> None:
    from .evidence import EVIDENCE_JSON, POST_TEXT

    src = run_dir / POST_TEXT
    bak = run_dir / POST_TEXT_BACKUP
    if src.is_file() and not bak.is_file():
        shutil.copy2(src, bak)
    ev = run_dir / EVIDENCE_JSON
    ev_bak = run_dir / EVIDENCE_BACKUP
    if ev.is_file() and not ev_bak.is_file():
        shutil.copy2(ev, ev_bak)


def _strip_file_digests(bundle: dict[str, Any]) -> dict[str, Any]:
    """File-backed hashes are recomputed on every verify; they are not operator-editable."""
    out = json.loads(json.dumps(bundle))
    probe = out.get("probe")
    if isinstance(probe, dict):
        probe.pop("image_sha256", None)
    match = out.get("match")
    if isinstance(match, dict):
        match.pop("image_sha256", None)
        match.pop("post_text_sha256", None)
    return out


def _apply_evidence_edit(run_dir: Path, stored: dict[str, Any]) -> dict[str, Any]:
    """Write operator JSON, then persist the rebuilt bundle (file hashes filled in)."""
    from .evidence import EVIDENCE_JSON, canonicalise, evidence_hash, rebuild_from_artifacts, write_bundle

    _ensure_backup(run_dir)
    prev: dict[str, Any] = {}
    path = run_dir / EVIDENCE_JSON
    if path.is_file():
        prev = json.loads(path.read_text(encoding="utf-8"))
    write_bundle(run_dir, stored)
    rebuilt = rebuild_from_artifacts(run_dir)
    write_bundle(run_dir, rebuilt)
    metadata_unchanged = canonicalise(_strip_file_digests(stored)) == canonicalise(
        _strip_file_digests(prev)
    )
    ignored = False
    s_probe, r_probe = stored.get("probe") or {}, rebuilt.get("probe") or {}
    s_match, r_match = stored.get("match") or {}, rebuilt.get("match") or {}
    for key, src, dst in (
        ("image_sha256", s_probe, r_probe),
        ("image_sha256", s_match, r_match),
        ("post_text_sha256", s_match, r_match),
    ):
        if key in src and src.get(key) != dst.get(key):
            ignored = True
            break
    return {
        "evidence": rebuilt,
        "evidence_hash": "0x" + evidence_hash(rebuilt).hex(),
        "digest_only_edit": metadata_unchanged and ignored,
    }


def _apply_pending_edits(run_dir: Path, payload: dict) -> dict[str, Any]:
    """Persist whatever is in the browser editor before hashing / verifying."""
    from .evidence import POST_TEXT, evidence_hash, rebuild_from_artifacts

    notes: dict[str, Any] = {}
    if payload.get("post_text") is not None:
        text = str(payload.get("post_text") or "")
        if len(text.encode("utf-8")) > POST_TEXT_CAP:
            raise FaceChainError("post text exceeds size cap")
        _ensure_backup(run_dir)
        (run_dir / POST_TEXT).write_text(text, encoding="utf-8")
    if payload.get("evidence_text"):
        notes = _apply_evidence_edit(run_dir, _parse_evidence_text(str(payload["evidence_text"])))
    rebuilt = rebuild_from_artifacts(run_dir)
    notes.setdefault("evidence", rebuilt)
    notes.setdefault("evidence_hash", "0x" + evidence_hash(rebuilt).hex())
    return notes


def _parse_evidence_text(text: str) -> dict[str, Any]:
    """Accept operator-edited JSON. Must still be a bundle rebuild can read."""
    raw = text.encode("utf-8")
    if len(raw) > EVIDENCE_CAP:
        raise FaceChainError("evidence.json exceeds size cap")
    try:
        stored = json.loads(text)
    except json.JSONDecodeError as exc:
        raise FaceChainError(f"evidence.json is not valid JSON: {exc.msg}") from exc
    if not isinstance(stored, dict):
        raise FaceChainError("evidence.json must be an object")
    for section in ("schema", "probe", "search", "match", "verification"):
        if section not in stored:
            raise FaceChainError("evidence bundle malformed", {"missing_key": section})
    return stored


def _tx_0x(raw: str) -> str:
    h = str(raw or "").strip()
    if h.startswith("0x") or h.startswith("0X"):
        return "0x" + h[2:].lower()
    return "0x" + h.lower() if h else ""


def _result_from_run_dir(run_dir: Path, cfg: Config) -> dict[str, Any]:
    """Rebuild the UI payload from files on disk so a saved run can be opened without re-scanning."""
    from .config import CHAIN_IDS
    from .evidence import (
        EVIDENCE_JSON,
        POST_TEXT,
        RECEIPT_JSON,
        evidence_hash,
        rebuild_from_artifacts,
        similarity_bps,
    )

    _ensure_backup(run_dir)
    stored = json.loads((run_dir / EVIDENCE_JSON).read_text(encoding="utf-8"))
    post_path = run_dir / POST_TEXT
    post_text = post_path.read_text(encoding="utf-8", errors="replace") if post_path.is_file() else ""
    bak = run_dir / POST_TEXT_BACKUP
    original = bak.read_text(encoding="utf-8", errors="replace") if bak.is_file() else post_text
    h = evidence_hash(rebuild_from_artifacts(run_dir))
    receipt = None
    rec_path = run_dir / RECEIPT_JSON
    if rec_path.is_file():
        receipt = json.loads(rec_path.read_text(encoding="utf-8"))

    match = stored.get("match") or {}
    ver = stored.get("verification") or {}
    search = stored.get("search") or {}
    net = (receipt or {}).get("network") or cfg.network
    contract = (receipt or {}).get("contract_address") or cfg.contract_address
    cosine = float(ver.get("cosine_similarity") or 0)
    anchored = None
    if receipt and receipt.get("evidence_hash"):
        anchored = receipt["evidence_hash"]
        if not str(anchored).startswith("0x"):
            anchored = "0x" + anchored
    return {
        "match": match.get("post_url"),
        "cosine": round(cosine, 4),
        "threshold": ver.get("threshold", cfg.threshold),
        "candidates": search.get("n_candidates"),
        "social": search.get("n_social"),
        "verified": search.get("n_face_verified"),
        "rows": [],
        "accounts": [],
        "resolved_handle": match.get("author_handle"),
        "resolved_profile": None,
        "linked": [],
        "evidence_hash": "0x" + h.hex(),
        "evidence": stored,
        "post_text": post_text,
        "original_post_text": original,
        "similarity_bps": similarity_bps(cosine),
        "record_id": None if receipt is None else receipt.get("record_id"),
        "tx": _tx_0x((receipt or {}).get("tx_hash") or ""),
        "awaiting_anchor": receipt is None,
        "network": net,
        "chain_id": CHAIN_IDS.get(net),
        "provider": search.get("provider"),
        "attempts": [],
        "contract": contract,
        "run_dir": _rel_to_project(run_dir),
        "verified_match": None,
        "anchored_hash": anchored,
        "loaded": True,
        **_artifact_inventory(run_dir),
    }


def _account_json(a) -> dict[str, Any]:
    payload = {
        "display": a.display,
        "platform": a.platform,
        "handle": a.handle,
        "profile_url": a.profile_url,
        "urls": list(a.urls),
        "origin": a.origin,
        "cosine": None if a.origin == "linked" else round(a.best_cosine, 4),
    }
    return payload


def _cfg(payload: dict) -> Config:
    from .cli import _load_dotenv

    _load_dotenv()
    return load_config(
        # Fall through to NETWORK in .env rather than forcing "local". Hardcoding the fallback
        # meant a configured testnet was silently ignored and runs anchored to a throwaway
        # in-process chain while the UI displayed the real contract address.
        network=payload.get("network") or None,
        threshold=payload.get("threshold"),
        search_provider=payload.get("provider") or None,
    )


def _run_job(job: Job, payload: dict) -> None:
    """Drive the same code path as `facechain run`."""
    from .evidence import evidence_hash, similarity_bps
    from .pipeline import run as run_pipeline

    try:
        cfg = _cfg(payload)
        image = safe_image_path(payload["image"]) if payload.get("image") else None

        if payload.get("capture"):
            from .capture import capture_face

            job.log("opening camera...", "step")
            image, score, attempts = capture_face(Path("capture.jpg"))
            job.log(f"captured {image.name}  det_score={score:.4f}  ({attempts} attempt)", "ok")

        if image is None:
            raise FaceChainError("no input image")

        from .providers import resolve_chain

        chain = " -> ".join(n for n, _ in resolve_chain(cfg))
        job.log(f"providers: {chain}   network={cfg.network}  tau={cfg.threshold}", "dim")
        job.log("detecting face and computing embedding...", "step")

        result = run_pipeline(image, cfg)
        job.log(
            f"lens returned {result.n_candidates} candidates, "
            f"{result.n_social} on social domains", "info"
        )
        job.log(f"independently embedded and scored {len(result.scored)} candidates", "step")

        rows = [
            {
                "url": s.candidate.page_url,
                "cosine": round(s.cosine, 4),
                "pass": s.cosine >= cfg.threshold,
            }
            for s in result.scored[:12]
        ]
        for s in result.expanded:
            rows.append({
                "url": s.candidate.page_url,
                "cosine": round(s.cosine, 4),
                "pass": True,
            })
        for r in rows:
            job.log(
                f"  {r['cosine']:.4f}  {'PASS  ' if r['pass'] else 'reject'}  {r['url'][:64]}",
                "ok" if r["pass"] else "dim",
            )

        from .profiles import group_accounts

        survivors = []
        for s in result.scored:
            if s.cosine < cfg.threshold:
                continue
            url = s.candidate.page_url
            if (
                result.resolved_profile
                and s.candidate.page_url == result.top.candidate.page_url
            ):
                url = result.resolved_profile
            survivors.append((url, s.cosine))
        survivors.extend((s.candidate.page_url, s.cosine) for s in result.expanded)
        accounts = group_accounts(survivors)
        linked = result.linked
        by_key = {(a.platform, a.handle): a for a in accounts}
        for extra in linked:
            key = (extra.platform, extra.handle)
            existing = by_key.get(key)
            if existing is None:
                accounts.append(extra)
                by_key[key] = extra
                continue
            for u in extra.urls:
                if u not in existing.urls:
                    existing.urls.append(u)
            if extra.profile_url and extra.profile_url not in existing.urls:
                existing.urls.append(extra.profile_url)
        if result.resolved_handle:
            job.log(f"account  @{result.resolved_handle}  {result.resolved_profile}", "ok")
            post = result.top.candidate.page_url
            for a in accounts:
                if a.handle == result.resolved_handle and post not in a.urls:
                    a.urls.append(post)

        for a in result.attempts:
            job.log(f"  {a['provider']}: {a['outcome'].replace('_', ' ')}"
                    + (f" (best {a['best']})" if "best" in a else ""), "dim")
        job.log(f"matched via {result.provider}", "ok")
        job.log(f"{len(survivors)} match(es) above threshold, "
                f"across {len(accounts)} account(s)", "ok")
        for a in accounts:
            job.log(f"  {a.display}  best cosine {a.best_cosine:.4f}", "ok")
            for u in a.urls:
                job.log(f"      {u}", "dim")

        if result.expanded:
            job.log(
                f"{len(result.expanded)} further account(s) from the verified handle "
                f"(each independently face-scored)",
                "info",
            )
            for s in result.expanded:
                job.log(
                    f"  {s.cosine:.4f}  PASS   {s.candidate.page_url[:64]}",
                    "ok",
                )

        if linked:
            job.log(
                f"{len(linked)} profile(s) linked from the verified page "
                f"(not independently face-scored)",
                "info",
            )
            for a in linked:
                job.log(f"  {a.display}", "ok")
                for u in a.urls:
                    job.log(f"      {u}", "dim")

        from .config import CHAIN_IDS
        from .evidence import POST_TEXT as POST_TEXT_FILE

        h = evidence_hash(result.bundle)
        post_text = (result.run_dir / POST_TEXT_FILE).read_text(encoding="utf-8", errors="replace")
        _ensure_backup(result.run_dir)
        rel_run = _rel_to_project(result.run_dir)
        job.log(
            "face match sealed locally. review the artifacts, then sign the on-chain tx.",
            "ok",
        )

        job.result = {
            "match": result.top.candidate.page_url,
            "cosine": round(result.top.cosine, 4),
            "threshold": cfg.threshold,
            "candidates": result.n_candidates,
            "social": result.n_social,
            "verified": result.n_verified,
            "rows": rows,
            "accounts": [_account_json(a) for a in accounts],
            "resolved_handle": result.resolved_handle,
            "resolved_profile": result.resolved_profile,
            "linked": [_account_json(a) for a in linked],
            "evidence_hash": "0x" + h.hex(),
            "evidence": result.bundle,
            "post_text": post_text,
            "original_post_text": post_text,
            "similarity_bps": similarity_bps(result.top.cosine),
            "record_id": None,
            "tx": None,
            "awaiting_anchor": True,
            "network": cfg.network,
            "chain_id": CHAIN_IDS.get(cfg.network),
            "provider": result.provider,
            "attempts": result.attempts,
            "contract": cfg.contract_address,
            "run_dir": rel_run,
            "verified_match": None,
            "loaded": False,
            **_artifact_inventory(result.run_dir),
        }
        job.ok = True

    except NoFaceDetectedError as exc:
        job.log(f"NoFaceDetectedError: {exc}", "err")
    except SearchProviderError as exc:
        job.log(f"SearchProviderError: {exc}", "err")
        job.log("a provider failure is not the same as 'no results found'", "dim")
    except NoVerifiedMatchError as exc:
        # `attempts` is structured data; printing the exception repr floods the UI with a dict.
        job.log("no candidate cleared the threshold in any provider", "warn")
        for a in exc.context.get("attempts") or []:
            if a.get("outcome") == "provider_error":
                job.log(f"  {a['provider']:<12} unavailable - {str(a.get('detail',''))[:64]}", "dim")
            else:
                job.log(
                    f"  {a['provider']:<12} {a.get('candidates',0):>4} candidates -> "
                    f"{a.get('social',0):>3} profiles -> {a.get('scored',0):>3} face-scored -> "
                    f"best {a.get('best',0):.4f}", "dim")
        job.log(f"threshold {exc.context.get('threshold')}; nothing was anchored.", "warn")
        job.log("this is the honest negative path, not an error.", "dim")
    except ChainError as exc:
        job.log(f"ChainError: {exc}", "err")
    except FaceChainError as exc:
        # Any other domain error is expected and reported plainly, without a traceback.
        job.log(f"{type(exc).__name__}: {exc}", "err")
    except Exception as exc:  # noqa: BLE001
        job.log(f"unexpected: {type(exc).__name__}: {exc}", "err")
        job.log(traceback.format_exc()[-400:], "dim")
    finally:
        job.done = True


def _write_receipt(run_dir: Path, *, record_id: int, tx: str, network: str,
                   contract: str, evidence_hash_hex: str) -> None:
    from .evidence import RECEIPT_JSON

    (run_dir / RECEIPT_JSON).write_text(json.dumps({
        "record_id": record_id, "tx_hash": tx, "network": network,
        "contract_address": contract, "evidence_hash": evidence_hash_hex,
    }, indent=2), encoding="utf-8")


def _current_hash(run_dir: Path) -> bytes:
    from .evidence import evidence_hash, rebuild_from_artifacts

    return evidence_hash(rebuild_from_artifacts(run_dir))


def create_app():
    app = FastAPI(title="facechain", docs_url=None, redoc_url=None)

    def _check_origin(request: Request) -> None:
        """Reject browser requests that did not originate from this page."""
        origin = request.headers.get("origin")
        if origin is None:
            return  # non-browser clients (curl, tests) send no Origin
        host = request.headers.get("host", "")
        if origin not in (f"http://{host}", f"https://{host}"):
            raise HTTPException(status_code=403, detail="cross-origin request rejected")

    @app.get("/")
    def index():
        # The CSRF token is injected per response rather than baked into the static file.
        html = (STATIC / "index.html").read_text()
        html = html.replace("__CSRF_TOKEN__", CSRF_TOKEN)
        return HTMLResponse(html)

    @app.get("/api/config")
    def config():
        cfg = _cfg({})
        from .config import CHAIN_IDS

        return {
            "provider": cfg.search_provider,
            "network": cfg.network,
            "threshold": cfg.threshold,
            "has_serpapi": bool(cfg.serpapi_key),
            "has_imgbb": bool(cfg.imgbb_key),
            "has_facecheck": bool(cfg.facecheck_key),
            "contract": cfg.contract_address,
            "chain_id": CHAIN_IDS.get(cfg.network),
        }

    @app.post("/api/upload")
    async def upload(
        request: Request,
        file: UploadFile = File(...),
        x_csrf_token: str = Header(default=""),
    ):
        """Accept an uploaded image and return a project-relative path.

        The client never chooses where the file lands. The stored name is generated, the
        extension comes from a fixed allowlist, and the content is checked against magic bytes --
        a supplied filename is treated as a label, never as a path.
        """
        _check_origin(request)
        if not secrets.compare_digest(x_csrf_token, CSRF_TOKEN):
            raise HTTPException(status_code=403, detail="missing or invalid CSRF token")

        suffix = Path(file.filename or "").suffix.lower()
        if suffix not in ALLOWED_SUFFIXES:
            raise HTTPException(
                status_code=400,
                detail=f"unsupported image type {suffix or '(none)'}",
            )

        data = await file.read(MAX_UPLOAD_BYTES + 1)
        if len(data) > MAX_UPLOAD_BYTES:
            raise HTTPException(status_code=413, detail="image exceeds 12 MB")
        if not data:
            raise HTTPException(status_code=400, detail="empty upload")
        if not _looks_like_image(data[:16]):
            raise HTTPException(status_code=400, detail="content is not a recognisable image")

        UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
        dest = UPLOAD_DIR / f"{uuid.uuid4().hex[:16]}{suffix}"
        dest.write_bytes(data)
        return {"path": _rel_to_project(dest), "bytes": len(data)}

    @app.post("/api/run")
    async def start(request: Request, payload: dict, x_csrf_token: str = Header(default="")):
        _check_origin(request)
        if not secrets.compare_digest(x_csrf_token, CSRF_TOKEN):
            raise HTTPException(status_code=403, detail="missing or invalid CSRF token")
        job = Job(id=uuid.uuid4().hex[:12])
        with _lock:
            _jobs[job.id] = job
        threading.Thread(target=_run_job, args=(job, payload), daemon=True).start()
        return {"job": job.id}

    @app.post("/api/tamper")
    async def tamper(request: Request, payload: dict, x_csrf_token: str = Header(default="")):
        """Run the tamper test on an existing anchored record, on request.

        Deliberately not part of /api/run. Flipping a byte of evidence is the one destructive-
        looking thing this tool does, and an operator should decide when it happens rather than
        watch it occur unprompted. The mutation still lands on a scratch copy -- the originals are
        never touched -- but the *decision* is now theirs.
        """
        _check_origin(request)
        if not secrets.compare_digest(x_csrf_token, CSRF_TOKEN):
            raise HTTPException(status_code=403, detail="missing or invalid CSRF token")

        from .chain.compile import compile_registry
        from .chain.deploy import signing_account
        from .chain.registry import Registry
        from .evidence import sha256_file
        from .verify import verify_record

        try:
            cfg = _cfg(payload)
            run_dir = safe_run_dir(str(payload.get("run_dir") or ""))
            record_id = int(payload.get("record_id"))

            before = {p.name: sha256_file(p) for p in sorted(run_dir.iterdir()) if p.is_file()}

            addr = _contract_address(cfg, payload)
            w3 = _web3(cfg)
            abi, _ = compile_registry()
            reg = Registry(w3, addr, list(abi),
                           account=signing_account(w3, cfg))

            intact = verify_record(reg, record_id, run_dir, cfg)
            bad = verify_record(reg, record_id, run_dir, cfg, tamper=True)

            after = {p.name: sha256_file(p) for p in sorted(run_dir.iterdir()) if p.is_file()}
        except FaceChainError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        except (TypeError, ValueError) as exc:
            raise HTTPException(status_code=400, detail="record_id must be an integer") from exc

        return {
            "onchain_hash": "0x" + bad.onchain_hash.hex(),
            "intact_hash": "0x" + intact.recomputed_hash.hex(),
            "tampered_hash": "0x" + bad.recomputed_hash.hex(),
            "detected": not bad.matches,
            # Proof the demonstration did not damage the real evidence.
            "originals_unchanged": before == after,
            "mutated_file": "post_text.txt",
        }

    @app.get("/api/runs")
    def list_runs():
        """Saved artifact folders, newest first, so a demo can open a previous scan."""
        root = PROJECT_ROOT / "artifacts"
        if not root.is_dir():
            return {"runs": []}
        items = []
        for d in sorted(root.iterdir(), key=lambda p: p.stat().st_mtime, reverse=True):
            if not d.is_dir() or not d.name.startswith("run-"):
                continue
            rec_data: dict[str, Any] = {}
            rec = d / "receipt.json"
            if rec.is_file():
                try:
                    rec_data = json.loads(rec.read_text(encoding="utf-8"))
                except json.JSONDecodeError:
                    rec_data = {}
            match_url = ""
            ev = d / "evidence.json"
            if ev.is_file():
                try:
                    match_url = json.loads(ev.read_text(encoding="utf-8")).get("match", {}).get(
                        "post_url", ""
                    )
                except json.JSONDecodeError:
                    match_url = ""
            items.append({
                "run_dir": _rel_to_project(d),
                "anchored": rec.is_file(),
                "record_id": rec_data.get("record_id"),
                "network": rec_data.get("network"),
                "match": match_url,
            })
        return {"runs": items}

    @app.get("/api/load")
    def load_run(run_dir: str = "", network: str | None = None):
        """Open an existing artifact folder in the UI without re-running the pipeline."""
        try:
            d = safe_run_dir(run_dir)
            cfg = _cfg({"network": network} if network else {})
            return _result_from_run_dir(d, cfg)
        except FaceChainError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        except (OSError, json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
            raise HTTPException(status_code=400, detail=f"could not load run: {exc}") from exc

    @app.get("/api/artifact/{name:path}")
    def artifact(name: str, run_dir: str = ""):
        """Serve one file from a run directory. Names are an allowlist, not a path."""
        media = _artifact_media_type(name)
        if media is None:
            raise HTTPException(status_code=404, detail="unknown artifact")
        try:
            d = safe_run_dir(run_dir)
        except FaceChainError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        path = (d / name).resolve()
        try:
            path.relative_to(d.resolve())
        except ValueError:
            raise HTTPException(status_code=400, detail="artifact path rejected") from None
        if not path.is_file():
            raise HTTPException(status_code=404, detail="artifact missing")
        return FileResponse(path, media_type=media, filename=path.name)

    @app.post("/api/post-text")
    async def save_post_text(request: Request, payload: dict, x_csrf_token: str = Header(default="")):
        """Overwrite post_text.txt in a run so the operator can tamper it in the browser."""
        _check_origin(request)
        if not secrets.compare_digest(x_csrf_token, CSRF_TOKEN):
            raise HTTPException(status_code=403, detail="missing or invalid CSRF token")
        from .evidence import POST_TEXT, evidence_hash, rebuild_from_artifacts

        text = str(payload.get("text") or "")
        if len(text.encode("utf-8")) > POST_TEXT_CAP:
            raise HTTPException(status_code=413, detail="post text exceeds size cap")
        try:
            run_dir = safe_run_dir(str(payload.get("run_dir") or ""))
        except FaceChainError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        _ensure_backup(run_dir)
        (run_dir / POST_TEXT).write_text(text, encoding="utf-8")
        rebuilt = rebuild_from_artifacts(run_dir)
        return {
            "ok": True,
            "evidence_hash": "0x" + evidence_hash(rebuilt).hex(),
            "post_text_sha256": rebuilt["match"]["post_text_sha256"],
        }

    @app.post("/api/post-text/restore")
    async def restore_post_text(request: Request, payload: dict, x_csrf_token: str = Header(default="")):
        """Put post_text.txt back to the copy taken before the first in-browser edit."""
        _check_origin(request)
        if not secrets.compare_digest(x_csrf_token, CSRF_TOKEN):
            raise HTTPException(status_code=403, detail="missing or invalid CSRF token")
        from .evidence import POST_TEXT, evidence_hash, rebuild_from_artifacts

        try:
            run_dir = safe_run_dir(str(payload.get("run_dir") or ""))
        except FaceChainError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        bak = run_dir / POST_TEXT_BACKUP
        if not bak.is_file():
            raise HTTPException(status_code=400, detail="no original post text saved")
        (run_dir / POST_TEXT).write_bytes(bak.read_bytes())
        rebuilt = rebuild_from_artifacts(run_dir)
        return {
            "ok": True,
            "post_text": bak.read_text(encoding="utf-8", errors="replace"),
            "evidence_hash": "0x" + evidence_hash(rebuilt).hex(),
            "post_text_sha256": rebuilt["match"]["post_text_sha256"],
        }

    @app.post("/api/evidence")
    async def save_evidence(request: Request, payload: dict, x_csrf_token: str = Header(default="")):
        """Overwrite evidence.json so the operator can tamper metadata in the browser."""
        _check_origin(request)
        if not secrets.compare_digest(x_csrf_token, CSRF_TOKEN):
            raise HTTPException(status_code=403, detail="missing or invalid CSRF token")

        try:
            run_dir = safe_run_dir(str(payload.get("run_dir") or ""))
            stored = _parse_evidence_text(str(payload.get("text") or ""))
        except FaceChainError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        result = _apply_evidence_edit(run_dir, stored)
        return {"ok": True, **result}

    @app.post("/api/evidence/restore")
    async def restore_evidence(request: Request, payload: dict, x_csrf_token: str = Header(default="")):
        """Put evidence.json back to the copy taken before the first in-browser edit."""
        _check_origin(request)
        if not secrets.compare_digest(x_csrf_token, CSRF_TOKEN):
            raise HTTPException(status_code=403, detail="missing or invalid CSRF token")
        from .evidence import EVIDENCE_JSON, evidence_hash, rebuild_from_artifacts

        try:
            run_dir = safe_run_dir(str(payload.get("run_dir") or ""))
        except FaceChainError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        bak = run_dir / EVIDENCE_BACKUP
        if not bak.is_file():
            raise HTTPException(status_code=400, detail="no original evidence.json saved")
        (run_dir / EVIDENCE_JSON).write_bytes(bak.read_bytes())
        rebuilt = rebuild_from_artifacts(run_dir)
        return {
            "ok": True,
            "evidence": rebuilt,
            "evidence_hash": "0x" + evidence_hash(rebuilt).hex(),
        }

    @app.post("/api/anchor/prepare")
    async def prepare_anchor(request: Request, payload: dict, x_csrf_token: str = Header(default="")):
        """Return an unsigned `anchor` call for MetaMask. Does not send a transaction."""
        _check_origin(request)
        if not secrets.compare_digest(x_csrf_token, CSRF_TOKEN):
            raise HTTPException(status_code=403, detail="missing or invalid CSRF token")
        from .chain.compile import compile_registry
        from .chain.deploy import make_web3
        from .chain.registry import encode_anchor_call
        from .config import CHAIN_IDS
        from .evidence import similarity_bps

        try:
            cfg = _cfg(payload)
            run_dir = safe_run_dir(str(payload.get("run_dir") or ""))
            cfg.require("contract_address")
            if cfg.network == "local":
                raise FaceChainError("MetaMask is for public networks; use local anchor instead")
            stored = json.loads((run_dir / "evidence.json").read_text(encoding="utf-8"))
            h = _current_hash(run_dir)
            post_url = stored["match"]["post_url"]
            bps = similarity_bps(float(stored["verification"]["cosine_similarity"]))
            w3 = make_web3(cfg)
            abi, _ = compile_registry()
            data = encode_anchor_call(w3, cfg.contract_address, list(abi), h, post_url, bps)
            to = w3.to_checksum_address(cfg.contract_address)
        except FaceChainError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        return {
            "to": to,
            "data": data if str(data).startswith("0x") else "0x" + str(data),
            "chain_id": CHAIN_IDS.get(cfg.network),
            "evidence_hash": "0x" + h.hex(),
            "post_url": post_url,
            "similarity_bps": bps,
        }

    @app.post("/api/anchor/confirm")
    async def confirm_anchor(request: Request, payload: dict, x_csrf_token: str = Header(default="")):
        """Wait for a wallet-submitted tx and record the receipt."""
        _check_origin(request)
        if not secrets.compare_digest(x_csrf_token, CSRF_TOKEN):
            raise HTTPException(status_code=403, detail="missing or invalid CSRF token")
        from .chain.compile import compile_registry
        from .chain.deploy import make_web3
        from .chain.registry import Registry

        try:
            cfg = _cfg(payload)
            run_dir = safe_run_dir(str(payload.get("run_dir") or ""))
            cfg.require("contract_address")
            raw = str(payload.get("tx_hash") or "").strip()
            if raw.startswith("0x"):
                raw = raw[2:]
            tx_bytes = bytes.fromhex(raw)
            w3 = make_web3(cfg)
            receipt = w3.eth.wait_for_transaction_receipt(tx_bytes, timeout=300)
            if int(receipt["status"]) != 1:
                raise FaceChainError("anchor transaction reverted")
            abi, _ = compile_registry()
            reg = Registry(w3, cfg.contract_address, list(abi))
            logs = reg._c.events.MatchAnchored().process_receipt(receipt)
            if not logs:
                raise FaceChainError("anchor emitted no MatchAnchored event")
            rid = int(logs[0]["args"]["id"])
            tx = "0x" + raw.lower()
            h = _current_hash(run_dir)
            _write_receipt(
                run_dir, record_id=rid, tx=tx, network=cfg.network,
                contract=reg.address, evidence_hash_hex=h.hex(),
            )
        except FaceChainError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        except ValueError as exc:
            raise HTTPException(status_code=400, detail="tx_hash must be hex") from exc
        return {
            "record_id": rid,
            "tx": tx,
            "contract": reg.address,
            "evidence_hash": "0x" + h.hex(),
            "network": cfg.network,
        }

    @app.post("/api/anchor/local")
    async def local_anchor(request: Request, payload: dict, x_csrf_token: str = Header(default="")):
        """Sign with the server wallet. Only for the in-process `local` chain."""
        _check_origin(request)
        if not secrets.compare_digest(x_csrf_token, CSRF_TOKEN):
            raise HTTPException(status_code=403, detail="missing or invalid CSRF token")
        from .chain.compile import compile_registry
        from .chain.deploy import deploy, signing_account
        from .chain.registry import Registry
        from .evidence import similarity_bps

        try:
            cfg = _cfg(payload)
            if cfg.network != "local":
                raise FaceChainError(
                    "public networks must be signed in MetaMask",
                    {"hint": "use the wallet button on sepolia / base-sepolia"},
                )
            run_dir = safe_run_dir(str(payload.get("run_dir") or ""))
            stored = json.loads((run_dir / "evidence.json").read_text(encoding="utf-8"))
            h = _current_hash(run_dir)
            post_url = stored["match"]["post_url"]
            bps = similarity_bps(float(stored["verification"]["cosine_similarity"]))
            w3 = _web3(cfg)
            abi, _ = compile_registry()
            # eth-tester cannot talk to a public CONTRACT_ADDRESS from .env.
            addr = _LOCAL.get("contract")
            if not addr:
                addr = deploy(w3, cfg)
                _LOCAL["contract"] = addr
            reg = Registry(w3, addr, list(abi), account=signing_account(w3, cfg))
            rid, tx = reg.anchor(h, post_url, bps)
            _write_receipt(
                run_dir, record_id=rid, tx=tx, network=cfg.network,
                contract=reg.address, evidence_hash_hex=h.hex(),
            )
        except FaceChainError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        return {
            "record_id": rid,
            "tx": tx,
            "contract": reg.address,
            "evidence_hash": "0x" + h.hex(),
            "network": cfg.network,
        }

    @app.post("/api/verify")
    async def verify_now(request: Request, payload: dict, x_csrf_token: str = Header(default="")):
        """Recompute the bundle from current files and compare to the on-chain record."""
        _check_origin(request)
        if not secrets.compare_digest(x_csrf_token, CSRF_TOKEN):
            raise HTTPException(status_code=403, detail="missing or invalid CSRF token")
        from .chain.compile import compile_registry
        from .chain.registry import Registry
        from .evidence import POST_TEXT
        from .verify import verify_record

        try:
            cfg = _cfg(payload)
            run_dir = safe_run_dir(str(payload.get("run_dir") or ""))
            record_id = int(payload.get("record_id"))
            pending = _apply_pending_edits(run_dir, payload)
            addr = _contract_address(cfg, payload)
            w3 = _web3(cfg)
            abi, _ = compile_registry()
            reg = Registry(w3, addr, list(abi))
            ok = verify_record(reg, record_id, run_dir, cfg)
        except FaceChainError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        except (TypeError, ValueError) as exc:
            raise HTTPException(status_code=400, detail="record_id must be an integer") from exc
        post_path = run_dir / POST_TEXT
        return {
            "onchain_hash": "0x" + ok.onchain_hash.hex(),
            "recomputed_hash": "0x" + ok.recomputed_hash.hex(),
            "matches": ok.matches,
            "post_url": ok.post_url,
            "record_id": ok.record_id,
            "evidence": pending.get("evidence"),
            "evidence_hash": pending.get("evidence_hash"),
            "digest_only_edit": pending.get("digest_only_edit", False),
            "post_text": post_path.read_text(encoding="utf-8", errors="replace") if post_path.is_file() else "",
        }

    @app.get("/api/job/{job_id}")
    def status(job_id: str):
        job = _jobs.get(job_id)
        if job is None:
            return JSONResponse({"error": "no such job"}, status_code=404)
        return {"lines": job.lines, "done": job.done, "ok": job.ok, "result": job.result}

    return app


def serve(host: str = "127.0.0.1", port: int = 8000) -> None:  # pragma: no cover
    import uvicorn

    uvicorn.run(create_app(), host=host, port=port, log_level="warning")
